In [119]:
import pandas as pd

In [120]:
customers = pd.read_csv(
    "../data/raw/olist_customers_dataset.csv"
)

In [121]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [122]:
customers.shape

(99441, 5)

In [123]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [124]:
customers["customer_id"].nunique()

99441

In [125]:
customers["customer_unique_id"].nunique()

96096

In [126]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [127]:
customers["customer_unique_id"].duplicated().sum()

np.int64(3345)

In [128]:
print("Unique customer_id:", customers["customer_id"].nunique())
print("Unique customer_unique_id:", customers["customer_unique_id"].nunique())
print("Duplicated customer_id:", customers["customer_id"].duplicated().sum())
print("Duplicated customer_unique_id:",customers["customer_unique_id"].duplicated().sum())

Unique customer_id: 99441
Unique customer_unique_id: 96096
Duplicated customer_id: 0
Duplicated customer_unique_id: 3345

## 2. Orders Table Reconnaissance

In [129]:
orders= pd.read_csv(
    "../data/raw/olist_orders_dataset.csv"
)

In [130]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [131]:
orders.shape

(99441, 8)

In [132]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [133]:
print("Unique order_id:", orders["order_id"].nunique())
print("Duplicated order_id:", orders["order_id"].duplicated().sum())
print("Unique customer_id:", orders["customer_id"].nunique())
print("Duplicated customer_id:", orders["customer_id"].duplicated().sum())

Unique order_id: 99441
Duplicated order_id: 0
Unique customer_id: 99441
Duplicated customer_id: 0

In [134]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

## 3. Order Items Table Reconnaissance

In [135]:
order_items = pd.read_csv(
    "../data/raw/olist_order_items_dataset.csv"
)

In [136]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [137]:
print("Shape:",order_items.shape)
print("Info:")
print(order_items.info())

Shape: (112650, 7)
Info:
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB
None

In [138]:
print("Duplicated orders:",order_items["order_id"].duplicated().sum())
print("Unique order_id:",order_items["order_id"].nunique())
print("Total order_id:",order_items["order_id"].count())

Duplicated orders: 13984
Unique order_id: 98666
Total order_id: 112650

In [139]:
print("Unique order_id:", order_items["order_id"].nunique())
print("Total order_id:",order_items["order_id"].count())
print("Unique product_id:",order_items["product_id"].nunique())
print("Total product_id:",order_items["product_id"].count())
print("Unique seller_id:", order_items["seller_id"].nunique())
print("Total seller_id:",order_items["seller_id"].count())

Unique order_id: 98666
Total order_id: 112650
Unique product_id: 32951
Total product_id: 112650
Unique seller_id: 3095
Total seller_id: 112650

In [140]:
print("Total order-item rows:",len(order_items))

Total order-item rows: 112650

In [141]:
order_items["order_id"].value_counts().head(10)

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
428a2f660dc84138d969ccd69a0ab6d5    15
9ef13efd6949e4573a18964dd1bbe7f5    15
73c8ab38f07dc94389065f7eba4f297a    14
9bdc4d4c71aa1de4606060929dee888c    14
37ee401157a3a0b28c9c6d0ed8c3b24b    13
2c2a19b5703863c908512d135aa6accc    12
3a213fcdfe7d98be74ea0dc05a8b31ae    12
Name: count, dtype: int64

In [142]:
order_items["price"].describe()

count    112650.000000
mean        120.653739
std         183.633928
min           0.850000
25%          39.900000
50%          74.990000
75%         134.900000
max        6735.000000
Name: price, dtype: float64

## 4. Products Table Reconnaissance

In [143]:
products  = pd.read_csv(
    "../data/raw/olist_products_dataset.csv"
)

In [144]:
products.head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
5,41d3672d4792049fa1779bb35283ed13,instrumentos_musicais,60.0,745.0,1.0,200.0,38.0,5.0,11.0
6,732bd381ad09e530fe0a5f457d81becb,cool_stuff,56.0,1272.0,4.0,18350.0,70.0,24.0,44.0
7,2548af3e6e77a690cf3eb6368e9ab61e,moveis_decoracao,56.0,184.0,2.0,900.0,40.0,8.0,40.0
8,37cc742be07708b53a98702e77a21a02,eletrodomesticos,57.0,163.0,1.0,400.0,27.0,13.0,17.0
9,8c92109888e8cdf9d66dc7e463025574,brinquedos,36.0,1156.0,1.0,600.0,17.0,10.0,12.0

In [145]:
products.shape

(32951, 9)

In [146]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [147]:
print("Unique product_id:",products["product_id"].nunique())
print("Duplicated product_id:",products["product_id"].duplicated().sum())

Unique product_id: 32951
Duplicated product_id: 0

In [148]:
products["product_category_name"].value_counts().head(10)

product_category_name
cama_mesa_banho           3029
esporte_lazer             2867
moveis_decoracao          2657
beleza_saude              2444
utilidades_domesticas     2335
automotivo                1900
informatica_acessorios    1639
brinquedos                1411
relogios_presentes        1329
telefonia                 1134
Name: count, dtype: int64

In [149]:
products["product_category_name"].isna().sum()

np.int64(610)

## 5. Sellers Table Reconnaissance

In [150]:
sellers = pd.read_csv(
    "../data/raw/olist_sellers_dataset.csv"
)

In [151]:
sellers.head(10)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
5,c240c4061717ac1806ae6ee72be3533b,20920,rio de janeiro,RJ
6,e49c26c3edfa46d227d5121a6b6e4d37,55325,brejao,PE
7,1b938a7ec6ac5061a66a3766e0e75f90,16304,penapolis,SP
8,768a86e36ad6aae3d03ee3c6433d61df,1529,sao paulo,SP
9,ccc4bbb5f32a6ab2b7066a4130f114e3,80310,curitiba,PR

In [152]:
sellers.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [153]:
print("Seller duplicates:",sellers["seller_id"].duplicated().sum())
print("Unique sellers:",sellers["seller_id"].nunique())
print("Total sellers:",sellers["seller_id"].count())

Seller duplicates: 0
Unique sellers: 3095
Total sellers: 3095

## Category Translation

In [154]:
category_translation = pd.read_csv(
    "../data/raw/product_category_name_translation.csv"
)

In [155]:
category_translation.head(10)

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor
5           esporte_lazer                sports_leisure
6              perfumaria                     perfumery
7   utilidades_domesticas                    housewares
8               telefonia                     telephony
9      relogios_presentes                 watches_gifts

In [156]:
##Category Translartion Analyse
print("Category Value Counts:")
print(category_translation.value_counts())
print()
print()

print("Category Info:")
print(category_translation.info())

print()
print()
print("Category Shape:")
print(category_translation.shape)

Category Value Counts:
product_category_name          product_category_name_english
beleza_saude                   health_beauty                    1
informatica_acessorios         computers_accessories            1
automotivo                     auto                             1
cama_mesa_banho                bed_bath_table                   1
moveis_decoracao               furniture_decor                  1
                                                               ..
flores                         flowers                          1
artes_e_artesanato             arts_and_craftmanship            1
fraldas_higiene                diapers_and_hygiene              1
fashion_roupa_infanto_juvenil  fashion_childrens_clothes        1
seguros_e_servicos             security_and_services            1
Name: count, Length: 71, dtype: int64


Category Info:
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB
None


Category Shape:
(71, 2)

In [157]:
##Product Analyse

print("Product Info :", products.info())
print("Product Shape :", products.shape)
print("Unique product_id:",products["product_id"].nunique())
print("Duplicated product_id:",products["product_id"].duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB
Product Info : None
Product Shape : (32951, 9)
Unique product_id: 32951
Duplicated product_id: 0

In [158]:
products["product_category_name"].isna().sum()

np.int64(610)

## 6.Order Payments Table Reconnaissance

In [159]:
payments=pd.read_csv(
    "../data/raw/olist_order_payments_dataset.csv"
)

In [160]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [161]:
## Payment Analysis
print("Payment Shape:",payments.shape)
print("Duplicated order_id:",payments["order_id"].duplicated().sum())
print("Unique order_id:", payments["order_id"].nunique())
print("Total order_id:", payments["order_id"].count())

Payment Shape: (103886, 5)
Duplicated order_id: 4446
Unique order_id: 99440
Total order_id: 103886

In [162]:
##Payment Type
payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [163]:
payments.describe()

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

## 7. Order Reviews Table Reconnaissance

In [164]:
reviews=pd.read_csv(
    "../data/raw/olist_order_reviews_dataset.csv"
)

In [165]:
reviews.head(10)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
5,15197aa66ff4d0650b5434f1b46cda19,b18dcdf73be66366873cd26c5724d1dc,1,NaN,NaN,2018-04-13 00:00:00,2018-04-16 00:39:37
6,07f9bee5d1b850860defd761afa7ff16,e48aa0d2dcec3a2e87348811bcfdf22b,5,NaN,NaN,2017-07-16 00:00:00,2017-07-18 19:30:34
7,7c6400515c67679fbee952a7525281ef,c31a859e34e3adac22f376954e19b39d,5,NaN,NaN,2018-08-14 00:00:00,2018-08-14 21:36:06
8,a3f6f7f6f433de0aefbb97da197c554c,9c214ac970e84273583ab523dfafd09b,5,NaN,NaN,2017-05-17 00:00:00,2017-05-18 12:05:37
9,8670d52e15e00043ae7de4c01cc2fe06,b9bf720beb4ab3728760088589c62129,4,recomendo,aparelho eficiente. no site a marca do aparelh...,2018-05-22 00:00:00,2018-05-23 16:45:47

In [166]:
##Review Analysis
print("Review Info:",reviews.info())
print("Review Shape:",reviews.shape)
print()
print("Total reviews:",reviews["review_id"].count())
print("Unique review_id:",reviews["review_id"].nunique())
print("Duplicated review_id:",reviews["review_id"].duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB
Review Info: None
Review Shape: (99224, 7)

Total reviews: 99224
Unique review_id: 98410
Duplicated review_id: 814

In [167]:
reviews["review_score"].value_counts()

review_score
5    57328
4    19142
1    11424
3     8179
2     3151
Name: count, dtype: int64

In [168]:
print("Missing review_comment_title:",reviews["review_comment_title"].isna().sum())
print("Misiing review_comment_message:",reviews["review_comment_message"].isna().sum())

Missing review_comment_title: 87656
Misiing review_comment_message: 58247

In [169]:
print("Review total order_id:",reviews["order_id"].count())
print("Review unique order_id:",reviews["order_id"].nunique())
print("Review duplicated order_id:",reviews["order_id"].duplicated().sum())

Review total order_id: 99224
Review unique order_id: 98673
Review duplicated order_id: 551

## 8. Initial Data Quality Assessment

### 8.1 Completeness Assessment

In [170]:
customers.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [171]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [172]:
order_items.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [173]:
products.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [174]:
sellers.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [175]:
payments.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [176]:
reviews.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [ ]:
(customers.isna().mean() * 100).sort_values(ascending=False)

customer_id                 0.0
customer_unique_id          0.0
customer_zip_code_prefix    0.0
customer_city               0.0
customer_state              0.0
dtype: float64

In [187]:
print(products.isna().sum().sort_values(ascending=False))
print()
print()
print((products.isna().mean()*100).sort_values(ascending=False))

product_category_name         610
product_description_lenght    610
product_name_lenght           610
product_photos_qty            610
product_weight_g                2
product_height_cm               2
product_length_cm               2
product_width_cm                2
product_id                      0
dtype: int64


product_category_name         1.851234
product_description_lenght    1.851234
product_name_lenght           1.851234
product_photos_qty            1.851234
product_weight_g              0.006070
product_height_cm             0.006070
product_length_cm             0.006070
product_width_cm              0.006070
product_id                    0.000000
dtype: float64

In [189]:
print(orders.isna().sum().sort_values(ascending=False)) 
print()
print()
print((orders.isna().mean()*100).sort_values(ascending=False))

order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_approved_at                 160
order_id                            0
order_purchase_timestamp            0
order_status                        0
customer_id                         0
order_estimated_delivery_date       0
dtype: int64


order_delivered_customer_date    2.981668
order_delivered_carrier_date     1.793023
order_approved_at                0.160899
order_id                         0.000000
order_purchase_timestamp         0.000000
order_status                     0.000000
customer_id                      0.000000
order_estimated_delivery_date    0.000000
dtype: float64

### Completeness Findings

- Customer identifiers contain no missing values.
- Order identifiers should be treated as mandatory fields.
- Some order lifecycle timestamps may legitimately be missing depending on order status.
- Product category completeness requires investigation.
- Review text fields may legitimately be missing because written comments are optional.

In [ ]:
products[
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [191]:
products[
    products["product_category_name"].isna()
].shape

(610, 9)

In [193]:
products[
    products["product_category_name"].isna()
].head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
244,e10758160da97891c2fdcbc35f0f031d,NaN,NaN,NaN,NaN,2200.0,16.0,2.0,11.0
294,39e3b9b12cd0bf8ee681bbc1c130feb5,NaN,NaN,NaN,NaN,300.0,16.0,7.0,11.0
299,794de06c32a626a5692ff50e4985d36f,NaN,NaN,NaN,NaN,300.0,18.0,8.0,14.0
347,7af3e2da474486a3519b0cba9dea8ad9,NaN,NaN,NaN,NaN,200.0,22.0,14.0,14.0
428,629beb8e7317703dcc5f35b5463fd20e,NaN,NaN,NaN,NaN,1400.0,25.0,25.0,25.0

In [196]:
products.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [197]:
products[
    products["product_weight_g"].isna()
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [198]:
products[
    products["product_height_cm"].isna()
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [201]:
orders[
   (orders["order_status"]=="delivered") & (orders["order_delivered_customer_date"].isna())
].shape

(8, 8)

In [207]:
orders[
    (orders["order_status"] == "delivered") &
    (orders["order_delivered_carrier_date"].isna())
].shape

(2, 8)

In [208]:
orders[
    (orders["order_status"] == "delivered") &
    (orders["order_approved_at"].isna())
].shape

(14, 8)

In [209]:
products[
    products["product_category_name"].isna()
][
    [
        "product_id",
        "product_category_name",
        "product_description_lenght",
        "product_name_lenght",
        "product_photos_qty",
        "product_weight_g",
        "product_height_cm",
        "product_length_cm",
        "product_width_cm"
    ]
].head(10)

,product_id,product_category_name,product_description_lenght,product_name_lenght,product_photos_qty,product_weight_g,product_height_cm,product_length_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,14.0,17.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,7.0,16.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,30.0,41.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,7.0,35.0,12.0
244,e10758160da97891c2fdcbc35f0f031d,NaN,NaN,NaN,NaN,2200.0,2.0,16.0,11.0
294,39e3b9b12cd0bf8ee681bbc1c130feb5,NaN,NaN,NaN,NaN,300.0,7.0,16.0,11.0
299,794de06c32a626a5692ff50e4985d36f,NaN,NaN,NaN,NaN,300.0,8.0,18.0,14.0
347,7af3e2da474486a3519b0cba9dea8ad9,NaN,NaN,NaN,NaN,200.0,14.0,22.0,14.0
428,629beb8e7317703dcc5f35b5463fd20e,NaN,NaN,NaN,NaN,1400.0,25.0,25.0,25.0

In [210]:
products[
    products["product_category_name"].isna()
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [215]:
customers.duplicated().sum()

np.int64(0)

In [216]:
orders.duplicated().sum()

np.int64(0)

In [217]:
products.duplicated().sum()

np.int64(0)

In [218]:
products["product_id"].duplicated().sum()

np.int64(0)

In [219]:
sellers.duplicated().sum()

np.int64(0)

In [221]:
reviews.duplicated().sum()

np.int64(0)

In [223]:
order_items["order_id"].duplicated().sum()

np.int64(13984)

In [224]:
order_items[
    ["order_id","order_item_id"]
].duplicated().sum()

np.int64(0)

In [225]:
payments.duplicated().sum()

np.int64(0)

In [227]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [231]:
payments[["order_id","payment_sequential"]].duplicated().sum()

np.int64(0)

In [232]:
reviews.duplicated().sum()

np.int64(0)

In [233]:
reviews["order_id"].duplicated().sum()

np.int64(551)

In [234]:
print("CUSTOMERS")
print("Duplicate customer_id:",
      customers["customer_id"].duplicated().sum())
print("Duplicate full rows:",
      customers.duplicated().sum())


print("\nORDERS")
print("Duplicate order_id:",
      orders["order_id"].duplicated().sum())
print("Duplicate full rows:",
      orders.duplicated().sum())


print("\nPRODUCTS")
print("Duplicate product_id:",
      products["product_id"].duplicated().sum())
print("Duplicate full rows:",
      products.duplicated().sum())


print("\nSELLERS")
print("Duplicate seller_id:",
      sellers["seller_id"].duplicated().sum())
print("Duplicate full rows:",
      sellers.duplicated().sum())


print("\nORDER ITEMS")
print("Duplicate order_id:",
      order_items["order_id"].duplicated().sum())
print(
    "Duplicate order_id + order_item_id:",
    order_items[["order_id", "order_item_id"]].duplicated().sum()
)


print("\nPAYMENTS")
print("Duplicate order_id:",
      payments["order_id"].duplicated().sum())
print(
    "Duplicate order_id + payment_sequential:",
    payments[["order_id", "payment_sequential"]].duplicated().sum()
)


print("\nREVIEWS")
print("Duplicate review_id:",
      reviews["review_id"].duplicated().sum())
print("Duplicate full rows:",
      reviews.duplicated().sum())

CUSTOMERS
Duplicate customer_id: 0
Duplicate full rows: 0

ORDERS
Duplicate order_id: 0
Duplicate full rows: 0

PRODUCTS
Duplicate product_id: 0
Duplicate full rows: 0

SELLERS
Duplicate seller_id: 0
Duplicate full rows: 0

ORDER ITEMS
Duplicate order_id: 13984
Duplicate order_id + order_item_id: 0

PAYMENTS
Duplicate order_id: 4446
Duplicate order_id + payment_sequential: 0

REVIEWS
Duplicate review_id: 814
Duplicate full rows: 0

In [245]:
duplicate_review_ids=reviews.loc[
    reviews["review_id"].duplicated(keep=False),"review_id"
].unique()

In [246]:
len(duplicate_review_ids)

789

In [247]:
reviews["review_id"].duplicated().sum()

np.int64(814)

In [254]:
reviews[["review_id", "order_id"]].duplicated().sum()

KeyError: ('review_id', 'order_id')